### PR TITLE
I propose its version of Function.prototype.bind

### PR DESCRIPTION
**Pull request by xguest**
I'm not sure I have a bad english
Hello!
We have talked.
I rewrote the code checked out, see.
Propose changes to improve.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks for the contribution! (If you click "Details" above, you'll see that there's some coding style changes that are needed).

Can you elaborate on how specifically this is an improvement over what we have now?

**Comment by xguest** [comment]
Thank you for attention,
I simplified the code.
It performs fewer operations.
All your tests pass.
One commit one change.
The files have a comment.

P.S. Which program to check coding style, and how to fix it.

**Comment by ljharb** [comment]
@xguest in the cloned repo, `npm test` should run the linter and the tests.

**Comment by xguest** [comment]
My code has no errors, I fixed, check please.
For Windows "npm test" does not work

**Comment by xguest** [comment]
ver
==>
Microsoft Windows [Version 6.1.7601]

npm version
==>
{ npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

'npm test' does not work

The Travis CI build
find all error in file ./test/index.js - did not change

**Comment by xguest** [comment]
My English is bad.
You ignore my offer?
Clarify please.

**Comment by ljharb** [comment]
@xguest What do you mean "does not work"? Can you share a gist of the output from running `npm test`? It should definitely run on windows.

The travis failures are linter errors - you may be right that the linter failures aren't part of your PR. I'll update master with the latest changes, and you can rebase your branch on top of that.

To clarify: how specifically do you feel this simplifies the code? Can you explain how you are counting the operations such that you believe yours is fewer? Note that the number of operations is irrelevant - only the overall performance is important. Do you have benchmarks showing that, on a multitude of pre-ES5 browsers, your version is faster than the current one?

**Comment by xguest** [comment]
Now jsperf not work.
But my teacher said - the number of transactions does not matter, only when the commands are different, but if they are just smaller, some are not satisfied.

My output:
I run script: [ljharb_function-bind.cmd.zip](https://github.com/ljharb/function-bind/files/346263/ljharb_function-bind.cmd.zip)
I get output:[ljharb_function-bind.log.zip](https://github.com/ljharb/function-bind/files/346265/ljharb_function-bind.log.zip)

**Comment by xguest** [comment]
@ljharb I installed locally jsPerf. You can offer a load test, or describe what you want to see. I can not understand how to test a single line of code.

**Pull request closed without merging**
